services:
  - type: web
    name: thoi-khoa-bieu
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: LOCAL_ADMIN_USERNAME
        sync: false
      - key: LOCAL_ADMIN_PASSWORD
        sync: false
